//Логирование
except Exception as e:
    logging.error('Got Exception %s %s', "one", "two", exc_info=e)

